/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserQuery {
  'roleFilter' : [] | [UserRole],
  'offset' : bigint,
  'suspendedFilter' : [] | [boolean],
  'limit' : bigint,
  'searchTerm' : [] | [string],
  'passportFilter' : [] | [boolean],
}
export interface AdminUserView { 'profile' : UserProfile }
export type Amount = bigint;
export interface AnsweredQuestion {
  'questionId' : bigint,
  'selectedOption' : bigint,
}
export interface AssessmentDefinition {
  'title' : string,
  'assessmentType' : AssessmentType,
  'description' : string,
  'totalQuestions' : bigint,
  'durationMinutes' : bigint,
}
export interface AssessmentProgress {
  'startedAt' : Timestamp,
  'submitted' : boolean,
  'userId' : UserId,
  'answers' : Array<AnsweredQuestion>,
  'assessmentType' : AssessmentType,
  'submittedAt' : [] | [Timestamp],
  'lastSavedAt' : Timestamp,
}
export interface AssessmentReport {
  'id' : UserId,
  'maxScore' : bigint,
  'userId' : UserId,
  'recommendations' : Array<CareerRecommendation>,
  'generatedAt' : Timestamp,
  'breakdown' : Array<ScoreBreakdown>,
  'assessmentType' : AssessmentType,
  'totalScore' : bigint,
  'summary' : string,
}
export type AssessmentType = { 'aptitude' : null } |
  { 'personality' : null } |
  { 'interest' : null };
export interface BlogPost {
  'id' : string,
  'title' : string,
  'body' : string,
  'published' : boolean,
  'createdAt' : Timestamp,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : [] | [Timestamp],
  'author' : string,
  'updatedAt' : Timestamp,
  'excerpt' : string,
}
export interface BlogPostInput {
  'title' : string,
  'body' : string,
  'published' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'excerpt' : string,
}
export interface CareerEntry {
  'id' : string,
  'relatedCareers' : Array<string>,
  'growth' : string,
  'subjects' : Array<string>,
  'published' : boolean,
  'name' : string,
  'educationPath' : Array<string>,
  'createdAt' : Timestamp,
  'slug' : string,
  'description' : string,
  'eligibility' : Array<string>,
  'businessOpportunities' : Array<string>,
  'updatedAt' : Timestamp,
  'introduction' : string,
  'category' : string,
  'topColleges' : Array<string>,
  'salaryRange' : SalaryRange,
  'entranceExams' : Array<string>,
  'skills' : Array<string>,
  'videos' : Array<string>,
  'futureScope' : string,
  'scholarships' : Array<string>,
  'aiImpact' : string,
}
export interface CareerEntryInput {
  'relatedCareers' : Array<string>,
  'growth' : string,
  'subjects' : Array<string>,
  'published' : boolean,
  'name' : string,
  'educationPath' : Array<string>,
  'slug' : string,
  'description' : string,
  'eligibility' : Array<string>,
  'businessOpportunities' : Array<string>,
  'introduction' : string,
  'category' : string,
  'topColleges' : Array<string>,
  'salaryRange' : SalaryRange,
  'entranceExams' : Array<string>,
  'skills' : Array<string>,
  'videos' : Array<string>,
  'futureScope' : string,
  'scholarships' : Array<string>,
  'aiImpact' : string,
}
export interface CareerRecommendation {
  'title' : string,
  'matchPercentage' : bigint,
  'rationale' : string,
  'careerId' : string,
}
export interface CareerSearchQuery {
  'publishedOnly' : boolean,
  'offset' : bigint,
  'limit' : bigint,
  'searchTerm' : [] | [string],
  'category' : [] | [string],
}
export interface CounsellorProfile {
  'id' : string,
  'bio' : string,
  'title' : string,
  'published' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'photoUrl' : [] | [string],
  'updatedAt' : Timestamp,
  'specializations' : Array<string>,
}
export interface CounsellorProfileInput {
  'bio' : string,
  'title' : string,
  'published' : boolean,
  'name' : string,
  'photoUrl' : [] | [string],
  'specializations' : Array<string>,
}
export interface Coupon {
  'active' : boolean,
  'couponType' : CouponType,
  'expiresAt' : [] | [Timestamp],
  'value' : bigint,
  'code' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'redemptions' : bigint,
  'maxRedemptions' : [] | [bigint],
}
export interface CouponInput {
  'active' : boolean,
  'couponType' : CouponType,
  'expiresAt' : [] | [Timestamp],
  'value' : bigint,
  'code' : string,
  'description' : [] | [string],
  'maxRedemptions' : [] | [bigint],
}
export type CouponType = { 'flat' : null } |
  { 'percent' : null };
export interface CouponValidation {
  'valid' : boolean,
  'discountAmount' : Amount,
  'reason' : [] | [string],
}
export type Currency = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Event {
  'id' : string,
  'title' : string,
  'registeredCount' : bigint,
  'startsAt' : Timestamp,
  'published' : boolean,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'capacity' : bigint,
  'location' : string,
  'endsAt' : Timestamp,
}
export interface EventInput {
  'title' : string,
  'startsAt' : Timestamp,
  'published' : boolean,
  'description' : string,
  'capacity' : bigint,
  'location' : string,
  'endsAt' : Timestamp,
}
export interface Invoice {
  'status' : PaymentStatus,
  'finalAmount' : Amount,
  'userId' : UserId,
  'discountAmount' : Amount,
  'invoiceNumber' : string,
  'currency' : Currency,
  'issuedAt' : Timestamp,
  'coupon' : [] | [Coupon],
  'amount' : Amount,
}
export interface Payment {
  'status' : PaymentStatus,
  'completedAt' : [] | [Timestamp],
  'couponCode' : [] | [string],
  'finalAmount' : Amount,
  'userId' : UserId,
  'discountAmount' : Amount,
  'createdAt' : Timestamp,
  'invoiceNumber' : string,
  'currency' : Currency,
  'stripeSessionId' : [] | [string],
  'amount' : Amount,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface ProofImage {
  'id' : bigint,
  'sortOrder' : bigint,
  'photoUrl' : string,
  'caption' : string,
  'category' : string,
  'altText' : string,
}
export interface RecordPaymentInput {
  'couponCode' : [] | [string],
  'currency' : Currency,
  'stripeSessionId' : [] | [string],
  'amount' : Amount,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface SalaryRange {
  'max' : bigint,
  'min' : bigint,
  'currency' : Currency,
}
export interface SaveProgressInput {
  'answers' : Array<AnsweredQuestion>,
  'assessmentType' : AssessmentType,
}
export interface ScoreBreakdown {
  'maxScore' : bigint,
  'dimensionLabel' : string,
  'score' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'emailVerified' : boolean,
  'displayName' : string,
  'createdAt' : Timestamp,
  'passportPurchasedAt' : [] | [Timestamp],
  'role' : UserRole,
  'email' : string,
  'updatedAt' : Timestamp,
  'suspended' : boolean,
  'passportPurchased' : boolean,
}
export interface UserProfileInput { 'displayName' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__assessmentsState' : ActorMethod<[], any>,
  '__careersState' : ActorMethod<[], any>,
  '__contentState' : ActorMethod<[], any>,
  '__couponsState' : ActorMethod<[], any>,
  '__paymentsState' : ActorMethod<[], any>,
  '__proofState' : ActorMethod<[], any>,
  '__reportsState' : ActorMethod<[], any>,
  '__usersState' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'adminListUsers' : ActorMethod<[AdminUserQuery], Array<AdminUserView>>,
  'adminSearchUsers' : ActorMethod<[AdminUserQuery], Array<AdminUserView>>,
  'adminSuspendUser' : ActorMethod<[Principal], UserProfile>,
  'adminUnsuspendUser' : ActorMethod<[Principal], UserProfile>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[BlogPostInput], BlogPost>,
  'createCareer' : ActorMethod<[CareerEntryInput], CareerEntry>,
  'createCounsellor' : ActorMethod<[CounsellorProfileInput], CounsellorProfile>,
  'createCoupon' : ActorMethod<[CouponInput], Coupon>,
  'createEvent' : ActorMethod<[EventInput], Event>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteCareer' : ActorMethod<[string], undefined>,
  'deleteCounsellor' : ActorMethod<[string], undefined>,
  'deleteCoupon' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'generateMyReport' : ActorMethod<[AssessmentType], AssessmentReport>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareer' : ActorMethod<[string], [] | [CareerEntry]>,
  'getCareerBySlug' : ActorMethod<[string], [] | [CareerEntry]>,
  'getCounsellor' : ActorMethod<[string], [] | [CounsellorProfile]>,
  'getEvent' : ActorMethod<[string], [] | [Event]>,
  'getMyInvoice' : ActorMethod<[string], [] | [Invoice]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyProgress' : ActorMethod<[AssessmentType], [] | [AssessmentProgress]>,
  'getMyReport' : ActorMethod<[AssessmentType], [] | [AssessmentReport]>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getReportForUser' : ActorMethod<
    [Principal, AssessmentType],
    [] | [AssessmentReport]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'listAssessmentDefinitions' : ActorMethod<[], Array<AssessmentDefinition>>,
  'listBlogPosts' : ActorMethod<[boolean], Array<BlogPost>>,
  'listCareers' : ActorMethod<[bigint, bigint], Array<CareerEntry>>,
  'listCounsellors' : ActorMethod<[boolean], Array<CounsellorProfile>>,
  'listCoupons' : ActorMethod<[], Array<Coupon>>,
  'listEvents' : ActorMethod<[boolean], Array<Event>>,
  'listMyInvoices' : ActorMethod<[], Array<Invoice>>,
  'listMyReports' : ActorMethod<[], Array<AssessmentReport>>,
  'listProofImages' : ActorMethod<[], Array<ProofImage>>,
  'listProofImagesByCategory' : ActorMethod<[string], Array<ProofImage>>,
  'markEmailVerified' : ActorMethod<[Principal], UserProfile>,
  'markPassportPurchased' : ActorMethod<[Principal], UserProfile>,
  'markPaymentCompleted' : ActorMethod<[string], Payment>,
  'recordMyPayment' : ActorMethod<[RecordPaymentInput], Payment>,
  'saveMyProgress' : ActorMethod<[SaveProgressInput], AssessmentProgress>,
  'searchCareers' : ActorMethod<[CareerSearchQuery], Array<CareerEntry>>,
  'submitMyAssessment' : ActorMethod<[AssessmentType], AssessmentProgress>,
  'updateBlogPost' : ActorMethod<[string, BlogPostInput], BlogPost>,
  'updateCareer' : ActorMethod<[string, CareerEntryInput], CareerEntry>,
  'updateCounsellor' : ActorMethod<
    [string, CounsellorProfileInput],
    CounsellorProfile
  >,
  'updateCoupon' : ActorMethod<[string, CouponInput], Coupon>,
  'updateEvent' : ActorMethod<[string, EventInput], Event>,
  'upsertMyProfile' : ActorMethod<[UserProfileInput], UserProfile>,
  'validateCoupon' : ActorMethod<[string, Amount], CouponValidation>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];