/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminUserQuery = IDL.Record({
  'roleFilter' : IDL.Opt(UserRole),
  'offset' : IDL.Nat,
  'suspendedFilter' : IDL.Opt(IDL.Bool),
  'limit' : IDL.Nat,
  'searchTerm' : IDL.Opt(IDL.Text),
  'passportFilter' : IDL.Opt(IDL.Bool),
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'emailVerified' : IDL.Bool,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'passportPurchasedAt' : IDL.Opt(Timestamp),
  'role' : UserRole,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'suspended' : IDL.Bool,
  'passportPurchased' : IDL.Bool,
});
export const AdminUserView = IDL.Record({ 'profile' : UserProfile });
export const BlogPostInput = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Opt(Timestamp),
  'author' : IDL.Text,
  'updatedAt' : Timestamp,
  'excerpt' : IDL.Text,
});
export const Currency = IDL.Text;
export const SalaryRange = IDL.Record({
  'max' : IDL.Nat,
  'min' : IDL.Nat,
  'currency' : Currency,
});
export const CareerEntryInput = IDL.Record({
  'relatedCareers' : IDL.Vec(IDL.Text),
  'growth' : IDL.Text,
  'subjects' : IDL.Vec(IDL.Text),
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'educationPath' : IDL.Vec(IDL.Text),
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Vec(IDL.Text),
  'businessOpportunities' : IDL.Vec(IDL.Text),
  'introduction' : IDL.Text,
  'category' : IDL.Text,
  'topColleges' : IDL.Vec(IDL.Text),
  'salaryRange' : SalaryRange,
  'entranceExams' : IDL.Vec(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
  'videos' : IDL.Vec(IDL.Text),
  'futureScope' : IDL.Text,
  'scholarships' : IDL.Vec(IDL.Text),
  'aiImpact' : IDL.Text,
});
export const CareerEntry = IDL.Record({
  'id' : IDL.Text,
  'relatedCareers' : IDL.Vec(IDL.Text),
  'growth' : IDL.Text,
  'subjects' : IDL.Vec(IDL.Text),
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'educationPath' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Vec(IDL.Text),
  'businessOpportunities' : IDL.Vec(IDL.Text),
  'updatedAt' : Timestamp,
  'introduction' : IDL.Text,
  'category' : IDL.Text,
  'topColleges' : IDL.Vec(IDL.Text),
  'salaryRange' : SalaryRange,
  'entranceExams' : IDL.Vec(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
  'videos' : IDL.Vec(IDL.Text),
  'futureScope' : IDL.Text,
  'scholarships' : IDL.Vec(IDL.Text),
  'aiImpact' : IDL.Text,
});
export const CounsellorProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'specializations' : IDL.Vec(IDL.Text),
});
export const CounsellorProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'photoUrl' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'specializations' : IDL.Vec(IDL.Text),
});
export const CouponType = IDL.Variant({
  'flat' : IDL.Null,
  'percent' : IDL.Null,
});
export const CouponInput = IDL.Record({
  'active' : IDL.Bool,
  'couponType' : CouponType,
  'expiresAt' : IDL.Opt(Timestamp),
  'value' : IDL.Nat,
  'code' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'maxRedemptions' : IDL.Opt(IDL.Nat),
});
export const Coupon = IDL.Record({
  'active' : IDL.Bool,
  'couponType' : CouponType,
  'expiresAt' : IDL.Opt(Timestamp),
  'value' : IDL.Nat,
  'code' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'redemptions' : IDL.Nat,
  'maxRedemptions' : IDL.Opt(IDL.Nat),
});
export const EventInput = IDL.Record({
  'title' : IDL.Text,
  'startsAt' : Timestamp,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'capacity' : IDL.Nat,
  'location' : IDL.Text,
  'endsAt' : Timestamp,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'registeredCount' : IDL.Nat,
  'startsAt' : Timestamp,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'capacity' : IDL.Nat,
  'location' : IDL.Text,
  'endsAt' : Timestamp,
});
export const AssessmentType = IDL.Variant({
  'aptitude' : IDL.Null,
  'personality' : IDL.Null,
  'interest' : IDL.Null,
});
export const CareerRecommendation = IDL.Record({
  'title' : IDL.Text,
  'matchPercentage' : IDL.Nat,
  'rationale' : IDL.Text,
  'careerId' : IDL.Text,
});
export const ScoreBreakdown = IDL.Record({
  'maxScore' : IDL.Nat,
  'dimensionLabel' : IDL.Text,
  'score' : IDL.Nat,
});
export const AssessmentReport = IDL.Record({
  'id' : UserId,
  'maxScore' : IDL.Nat,
  'userId' : UserId,
  'recommendations' : IDL.Vec(CareerRecommendation),
  'generatedAt' : Timestamp,
  'breakdown' : IDL.Vec(ScoreBreakdown),
  'assessmentType' : AssessmentType,
  'totalScore' : IDL.Nat,
  'summary' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Amount = IDL.Nat;
export const Invoice = IDL.Record({
  'status' : PaymentStatus,
  'finalAmount' : Amount,
  'userId' : UserId,
  'discountAmount' : Amount,
  'invoiceNumber' : IDL.Text,
  'currency' : Currency,
  'issuedAt' : Timestamp,
  'coupon' : IDL.Opt(Coupon),
  'amount' : Amount,
});
export const AnsweredQuestion = IDL.Record({
  'questionId' : IDL.Nat,
  'selectedOption' : IDL.Nat,
});
export const AssessmentProgress = IDL.Record({
  'startedAt' : Timestamp,
  'submitted' : IDL.Bool,
  'userId' : UserId,
  'answers' : IDL.Vec(AnsweredQuestion),
  'assessmentType' : AssessmentType,
  'submittedAt' : IDL.Opt(Timestamp),
  'lastSavedAt' : Timestamp,
});
export const AssessmentDefinition = IDL.Record({
  'title' : IDL.Text,
  'assessmentType' : AssessmentType,
  'description' : IDL.Text,
  'totalQuestions' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
});
export const ProofImage = IDL.Record({
  'id' : IDL.Nat,
  'sortOrder' : IDL.Nat,
  'photoUrl' : IDL.Text,
  'caption' : IDL.Text,
  'category' : IDL.Text,
  'altText' : IDL.Text,
});
export const Payment = IDL.Record({
  'status' : PaymentStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'couponCode' : IDL.Opt(IDL.Text),
  'finalAmount' : Amount,
  'userId' : UserId,
  'discountAmount' : Amount,
  'createdAt' : Timestamp,
  'invoiceNumber' : IDL.Text,
  'currency' : Currency,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'amount' : Amount,
});
export const RecordPaymentInput = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'currency' : Currency,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'amount' : Amount,
});
export const SaveProgressInput = IDL.Record({
  'answers' : IDL.Vec(AnsweredQuestion),
  'assessmentType' : AssessmentType,
});
export const CareerSearchQuery = IDL.Record({
  'publishedOnly' : IDL.Bool,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const UserProfileInput = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});
export const CouponValidation = IDL.Record({
  'valid' : IDL.Bool,
  'discountAmount' : Amount,
  'reason' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__assessmentsState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__careersState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__contentState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__couponsState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__paymentsState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__proofState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__reportsState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__usersState' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'adminListUsers' : IDL.Func(
      [AdminUserQuery],
      [IDL.Vec(AdminUserView)],
      ['query'],
    ),
  'adminSearchUsers' : IDL.Func(
      [AdminUserQuery],
      [IDL.Vec(AdminUserView)],
      ['query'],
    ),
  'adminSuspendUser' : IDL.Func([IDL.Principal], [UserProfile], []),
  'adminUnsuspendUser' : IDL.Func([IDL.Principal], [UserProfile], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([BlogPostInput], [BlogPost], []),
  'createCareer' : IDL.Func([CareerEntryInput], [CareerEntry], []),
  'createCounsellor' : IDL.Func(
      [CounsellorProfileInput],
      [CounsellorProfile],
      [],
    ),
  'createCoupon' : IDL.Func([CouponInput], [Coupon], []),
  'createEvent' : IDL.Func([EventInput], [Event], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteCareer' : IDL.Func([IDL.Text], [], []),
  'deleteCounsellor' : IDL.Func([IDL.Text], [], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'generateMyReport' : IDL.Func([AssessmentType], [AssessmentReport], []),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareer' : IDL.Func([IDL.Text], [IDL.Opt(CareerEntry)], ['query']),
  'getCareerBySlug' : IDL.Func([IDL.Text], [IDL.Opt(CareerEntry)], ['query']),
  'getCounsellor' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CounsellorProfile)],
      ['query'],
    ),
  'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getMyInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyProgress' : IDL.Func(
      [AssessmentType],
      [IDL.Opt(AssessmentProgress)],
      [],
    ),
  'getMyReport' : IDL.Func([AssessmentType], [IDL.Opt(AssessmentReport)], []),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getReportForUser' : IDL.Func(
      [IDL.Principal, AssessmentType],
      [IDL.Opt(AssessmentReport)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listAssessmentDefinitions' : IDL.Func(
      [],
      [IDL.Vec(AssessmentDefinition)],
      ['query'],
    ),
  'listBlogPosts' : IDL.Func([IDL.Bool], [IDL.Vec(BlogPost)], ['query']),
  'listCareers' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CareerEntry)],
      ['query'],
    ),
  'listCounsellors' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(CounsellorProfile)],
      ['query'],
    ),
  'listCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'listEvents' : IDL.Func([IDL.Bool], [IDL.Vec(Event)], ['query']),
  'listMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listMyReports' : IDL.Func([], [IDL.Vec(AssessmentReport)], []),
  'listProofImages' : IDL.Func([], [IDL.Vec(ProofImage)], ['query']),
  'listProofImagesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProofImage)],
      ['query'],
    ),
  'markEmailVerified' : IDL.Func([IDL.Principal], [UserProfile], []),
  'markPassportPurchased' : IDL.Func([IDL.Principal], [UserProfile], []),
  'markPaymentCompleted' : IDL.Func([IDL.Text], [Payment], []),
  'recordMyPayment' : IDL.Func([RecordPaymentInput], [Payment], []),
  'saveMyProgress' : IDL.Func([SaveProgressInput], [AssessmentProgress], []),
  'searchCareers' : IDL.Func(
      [CareerSearchQuery],
      [IDL.Vec(CareerEntry)],
      ['query'],
    ),
  'submitMyAssessment' : IDL.Func([AssessmentType], [AssessmentProgress], []),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPostInput], [BlogPost], []),
  'updateCareer' : IDL.Func([IDL.Text, CareerEntryInput], [CareerEntry], []),
  'updateCounsellor' : IDL.Func(
      [IDL.Text, CounsellorProfileInput],
      [CounsellorProfile],
      [],
    ),
  'updateCoupon' : IDL.Func([IDL.Text, CouponInput], [Coupon], []),
  'updateEvent' : IDL.Func([IDL.Text, EventInput], [Event], []),
  'upsertMyProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
  'validateCoupon' : IDL.Func(
      [IDL.Text, Amount],
      [CouponValidation],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminUserQuery = IDL.Record({
    'roleFilter' : IDL.Opt(UserRole),
    'offset' : IDL.Nat,
    'suspendedFilter' : IDL.Opt(IDL.Bool),
    'limit' : IDL.Nat,
    'searchTerm' : IDL.Opt(IDL.Text),
    'passportFilter' : IDL.Opt(IDL.Bool),
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'emailVerified' : IDL.Bool,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'passportPurchasedAt' : IDL.Opt(Timestamp),
    'role' : UserRole,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'suspended' : IDL.Bool,
    'passportPurchased' : IDL.Bool,
  });
  const AdminUserView = IDL.Record({ 'profile' : UserProfile });
  const BlogPostInput = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Opt(Timestamp),
    'author' : IDL.Text,
    'updatedAt' : Timestamp,
    'excerpt' : IDL.Text,
  });
  const Currency = IDL.Text;
  const SalaryRange = IDL.Record({
    'max' : IDL.Nat,
    'min' : IDL.Nat,
    'currency' : Currency,
  });
  const CareerEntryInput = IDL.Record({
    'relatedCareers' : IDL.Vec(IDL.Text),
    'growth' : IDL.Text,
    'subjects' : IDL.Vec(IDL.Text),
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'educationPath' : IDL.Vec(IDL.Text),
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Vec(IDL.Text),
    'businessOpportunities' : IDL.Vec(IDL.Text),
    'introduction' : IDL.Text,
    'category' : IDL.Text,
    'topColleges' : IDL.Vec(IDL.Text),
    'salaryRange' : SalaryRange,
    'entranceExams' : IDL.Vec(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
    'videos' : IDL.Vec(IDL.Text),
    'futureScope' : IDL.Text,
    'scholarships' : IDL.Vec(IDL.Text),
    'aiImpact' : IDL.Text,
  });
  const CareerEntry = IDL.Record({
    'id' : IDL.Text,
    'relatedCareers' : IDL.Vec(IDL.Text),
    'growth' : IDL.Text,
    'subjects' : IDL.Vec(IDL.Text),
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'educationPath' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Vec(IDL.Text),
    'businessOpportunities' : IDL.Vec(IDL.Text),
    'updatedAt' : Timestamp,
    'introduction' : IDL.Text,
    'category' : IDL.Text,
    'topColleges' : IDL.Vec(IDL.Text),
    'salaryRange' : SalaryRange,
    'entranceExams' : IDL.Vec(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
    'videos' : IDL.Vec(IDL.Text),
    'futureScope' : IDL.Text,
    'scholarships' : IDL.Vec(IDL.Text),
    'aiImpact' : IDL.Text,
  });
  const CounsellorProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'specializations' : IDL.Vec(IDL.Text),
  });
  const CounsellorProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'photoUrl' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'specializations' : IDL.Vec(IDL.Text),
  });
  const CouponType = IDL.Variant({ 'flat' : IDL.Null, 'percent' : IDL.Null });
  const CouponInput = IDL.Record({
    'active' : IDL.Bool,
    'couponType' : CouponType,
    'expiresAt' : IDL.Opt(Timestamp),
    'value' : IDL.Nat,
    'code' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'maxRedemptions' : IDL.Opt(IDL.Nat),
  });
  const Coupon = IDL.Record({
    'active' : IDL.Bool,
    'couponType' : CouponType,
    'expiresAt' : IDL.Opt(Timestamp),
    'value' : IDL.Nat,
    'code' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'redemptions' : IDL.Nat,
    'maxRedemptions' : IDL.Opt(IDL.Nat),
  });
  const EventInput = IDL.Record({
    'title' : IDL.Text,
    'startsAt' : Timestamp,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'capacity' : IDL.Nat,
    'location' : IDL.Text,
    'endsAt' : Timestamp,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'registeredCount' : IDL.Nat,
    'startsAt' : Timestamp,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'capacity' : IDL.Nat,
    'location' : IDL.Text,
    'endsAt' : Timestamp,
  });
  const AssessmentType = IDL.Variant({
    'aptitude' : IDL.Null,
    'personality' : IDL.Null,
    'interest' : IDL.Null,
  });
  const CareerRecommendation = IDL.Record({
    'title' : IDL.Text,
    'matchPercentage' : IDL.Nat,
    'rationale' : IDL.Text,
    'careerId' : IDL.Text,
  });
  const ScoreBreakdown = IDL.Record({
    'maxScore' : IDL.Nat,
    'dimensionLabel' : IDL.Text,
    'score' : IDL.Nat,
  });
  const AssessmentReport = IDL.Record({
    'id' : UserId,
    'maxScore' : IDL.Nat,
    'userId' : UserId,
    'recommendations' : IDL.Vec(CareerRecommendation),
    'generatedAt' : Timestamp,
    'breakdown' : IDL.Vec(ScoreBreakdown),
    'assessmentType' : AssessmentType,
    'totalScore' : IDL.Nat,
    'summary' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Amount = IDL.Nat;
  const Invoice = IDL.Record({
    'status' : PaymentStatus,
    'finalAmount' : Amount,
    'userId' : UserId,
    'discountAmount' : Amount,
    'invoiceNumber' : IDL.Text,
    'currency' : Currency,
    'issuedAt' : Timestamp,
    'coupon' : IDL.Opt(Coupon),
    'amount' : Amount,
  });
  const AnsweredQuestion = IDL.Record({
    'questionId' : IDL.Nat,
    'selectedOption' : IDL.Nat,
  });
  const AssessmentProgress = IDL.Record({
    'startedAt' : Timestamp,
    'submitted' : IDL.Bool,
    'userId' : UserId,
    'answers' : IDL.Vec(AnsweredQuestion),
    'assessmentType' : AssessmentType,
    'submittedAt' : IDL.Opt(Timestamp),
    'lastSavedAt' : Timestamp,
  });
  const AssessmentDefinition = IDL.Record({
    'title' : IDL.Text,
    'assessmentType' : AssessmentType,
    'description' : IDL.Text,
    'totalQuestions' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
  });
  const ProofImage = IDL.Record({
    'id' : IDL.Nat,
    'sortOrder' : IDL.Nat,
    'photoUrl' : IDL.Text,
    'caption' : IDL.Text,
    'category' : IDL.Text,
    'altText' : IDL.Text,
  });
  const Payment = IDL.Record({
    'status' : PaymentStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'couponCode' : IDL.Opt(IDL.Text),
    'finalAmount' : Amount,
    'userId' : UserId,
    'discountAmount' : Amount,
    'createdAt' : Timestamp,
    'invoiceNumber' : IDL.Text,
    'currency' : Currency,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'amount' : Amount,
  });
  const RecordPaymentInput = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'currency' : Currency,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'amount' : Amount,
  });
  const SaveProgressInput = IDL.Record({
    'answers' : IDL.Vec(AnsweredQuestion),
    'assessmentType' : AssessmentType,
  });
  const CareerSearchQuery = IDL.Record({
    'publishedOnly' : IDL.Bool,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const UserProfileInput = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  const CouponValidation = IDL.Record({
    'valid' : IDL.Bool,
    'discountAmount' : Amount,
    'reason' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__assessmentsState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__careersState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__contentState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__couponsState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__paymentsState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__proofState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__reportsState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__usersState' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'adminListUsers' : IDL.Func(
        [AdminUserQuery],
        [IDL.Vec(AdminUserView)],
        ['query'],
      ),
    'adminSearchUsers' : IDL.Func(
        [AdminUserQuery],
        [IDL.Vec(AdminUserView)],
        ['query'],
      ),
    'adminSuspendUser' : IDL.Func([IDL.Principal], [UserProfile], []),
    'adminUnsuspendUser' : IDL.Func([IDL.Principal], [UserProfile], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([BlogPostInput], [BlogPost], []),
    'createCareer' : IDL.Func([CareerEntryInput], [CareerEntry], []),
    'createCounsellor' : IDL.Func(
        [CounsellorProfileInput],
        [CounsellorProfile],
        [],
      ),
    'createCoupon' : IDL.Func([CouponInput], [Coupon], []),
    'createEvent' : IDL.Func([EventInput], [Event], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteCareer' : IDL.Func([IDL.Text], [], []),
    'deleteCounsellor' : IDL.Func([IDL.Text], [], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'generateMyReport' : IDL.Func([AssessmentType], [AssessmentReport], []),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareer' : IDL.Func([IDL.Text], [IDL.Opt(CareerEntry)], ['query']),
    'getCareerBySlug' : IDL.Func([IDL.Text], [IDL.Opt(CareerEntry)], ['query']),
    'getCounsellor' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CounsellorProfile)],
        ['query'],
      ),
    'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getMyInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyProgress' : IDL.Func(
        [AssessmentType],
        [IDL.Opt(AssessmentProgress)],
        [],
      ),
    'getMyReport' : IDL.Func([AssessmentType], [IDL.Opt(AssessmentReport)], []),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getReportForUser' : IDL.Func(
        [IDL.Principal, AssessmentType],
        [IDL.Opt(AssessmentReport)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listAssessmentDefinitions' : IDL.Func(
        [],
        [IDL.Vec(AssessmentDefinition)],
        ['query'],
      ),
    'listBlogPosts' : IDL.Func([IDL.Bool], [IDL.Vec(BlogPost)], ['query']),
    'listCareers' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CareerEntry)],
        ['query'],
      ),
    'listCounsellors' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(CounsellorProfile)],
        ['query'],
      ),
    'listCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'listEvents' : IDL.Func([IDL.Bool], [IDL.Vec(Event)], ['query']),
    'listMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listMyReports' : IDL.Func([], [IDL.Vec(AssessmentReport)], []),
    'listProofImages' : IDL.Func([], [IDL.Vec(ProofImage)], ['query']),
    'listProofImagesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProofImage)],
        ['query'],
      ),
    'markEmailVerified' : IDL.Func([IDL.Principal], [UserProfile], []),
    'markPassportPurchased' : IDL.Func([IDL.Principal], [UserProfile], []),
    'markPaymentCompleted' : IDL.Func([IDL.Text], [Payment], []),
    'recordMyPayment' : IDL.Func([RecordPaymentInput], [Payment], []),
    'saveMyProgress' : IDL.Func([SaveProgressInput], [AssessmentProgress], []),
    'searchCareers' : IDL.Func(
        [CareerSearchQuery],
        [IDL.Vec(CareerEntry)],
        ['query'],
      ),
    'submitMyAssessment' : IDL.Func([AssessmentType], [AssessmentProgress], []),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPostInput], [BlogPost], []),
    'updateCareer' : IDL.Func([IDL.Text, CareerEntryInput], [CareerEntry], []),
    'updateCounsellor' : IDL.Func(
        [IDL.Text, CounsellorProfileInput],
        [CounsellorProfile],
        [],
      ),
    'updateCoupon' : IDL.Func([IDL.Text, CouponInput], [Coupon], []),
    'updateEvent' : IDL.Func([IDL.Text, EventInput], [Event], []),
    'upsertMyProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
    'validateCoupon' : IDL.Func(
        [IDL.Text, Amount],
        [CouponValidation],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };