/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import type { ExternalBlob } from "@caffeineai/object-storage";
export type { ExternalBlob } from "@caffeineai/object-storage";
export interface AdminUserQuery {
    roleFilter?: UserRole;
    offset: bigint;
    suspendedFilter?: boolean;
    limit: bigint;
    searchTerm?: string;
    passportFilter?: boolean;
}
export interface ScoreBreakdown {
    maxScore: bigint;
    dimensionLabel: string;
    score: bigint;
}
export type Timestamp = bigint;
export interface BlogPostInput {
    title: string;
    body: string;
    published: boolean;
    slug: string;
    tags: Array<string>;
    author: string;
    excerpt: string;
}
export type Currency = string;
export interface AnsweredQuestion {
    questionId: bigint;
    selectedOption: bigint;
}
export interface CareerEntry {
    id: string;
    relatedCareers: Array<string>;
    growth: string;
    subjects: Array<string>;
    published: boolean;
    name: string;
    educationPath: Array<string>;
    createdAt: Timestamp;
    slug: string;
    description: string;
    eligibility: Array<string>;
    businessOpportunities: Array<string>;
    updatedAt: Timestamp;
    introduction: string;
    category: string;
    topColleges: Array<string>;
    salaryRange: SalaryRange;
    entranceExams: Array<string>;
    skills: Array<string>;
    videos: Array<string>;
    futureScope: string;
    scholarships: Array<string>;
    aiImpact: string;
}
export interface AssessmentProgress {
    startedAt: Timestamp;
    submitted: boolean;
    userId: UserId;
    answers: Array<AnsweredQuestion>;
    assessmentType: AssessmentType;
    submittedAt?: Timestamp;
    lastSavedAt: Timestamp;
}
export interface CareerSearchQuery {
    publishedOnly: boolean;
    offset: bigint;
    limit: bigint;
    searchTerm?: string;
    category?: string;
}
export interface CouponValidation {
    valid: boolean;
    discountAmount: Amount;
    reason?: string;
}
export interface CareerEntryInput {
    relatedCareers: Array<string>;
    growth: string;
    subjects: Array<string>;
    published: boolean;
    name: string;
    educationPath: Array<string>;
    slug: string;
    description: string;
    eligibility: Array<string>;
    businessOpportunities: Array<string>;
    introduction: string;
    category: string;
    topColleges: Array<string>;
    salaryRange: SalaryRange;
    entranceExams: Array<string>;
    skills: Array<string>;
    videos: Array<string>;
    futureScope: string;
    scholarships: Array<string>;
    aiImpact: string;
}
export interface SalaryRange {
    max: bigint;
    min: bigint;
    currency: Currency;
}
export interface BlogPost {
    id: string;
    title: string;
    body: string;
    published: boolean;
    createdAt: Timestamp;
    slug: string;
    tags: Array<string>;
    publishedAt?: Timestamp;
    author: string;
    updatedAt: Timestamp;
    excerpt: string;
}
export interface RecordPaymentInput {
    couponCode?: string;
    currency: Currency;
    stripeSessionId?: string;
    amount: Amount;
}
export interface Coupon {
    active: boolean;
    couponType: CouponType;
    expiresAt?: Timestamp;
    value: bigint;
    code: string;
    createdAt: Timestamp;
    description?: string;
    redemptions: bigint;
    maxRedemptions?: bigint;
}
export interface Event {
    id: string;
    title: string;
    registeredCount: bigint;
    startsAt: Timestamp;
    published: boolean;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    capacity: bigint;
    location: string;
    endsAt: Timestamp;
}
export interface ProofImage {
    id: bigint;
    sortOrder: bigint;
    photoUrl: string;
    caption: string;
    category: string;
    altText: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Payment {
    status: PaymentStatus;
    completedAt?: Timestamp;
    couponCode?: string;
    finalAmount: Amount;
    userId: UserId;
    discountAmount: Amount;
    createdAt: Timestamp;
    invoiceNumber: string;
    currency: Currency;
    stripeSessionId?: string;
    amount: Amount;
}
export interface Invoice {
    status: PaymentStatus;
    finalAmount: Amount;
    userId: UserId;
    discountAmount: Amount;
    invoiceNumber: string;
    currency: Currency;
    issuedAt: Timestamp;
    coupon?: Coupon;
    amount: Amount;
}
export interface SaveProgressInput {
    answers: Array<AnsweredQuestion>;
    assessmentType: AssessmentType;
}
export interface CounsellorProfileInput {
    bio: string;
    title: string;
    published: boolean;
    name: string;
    photoUrl?: string;
    specializations: Array<string>;
}
export type Amount = bigint;
export type UserId = Principal;
export interface AdminUserView {
    profile: UserProfile;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface EventInput {
    title: string;
    startsAt: Timestamp;
    published: boolean;
    description: string;
    capacity: bigint;
    location: string;
    endsAt: Timestamp;
}
export interface AssessmentDefinition {
    title: string;
    assessmentType: AssessmentType;
    description: string;
    totalQuestions: bigint;
    durationMinutes: bigint;
}
export interface CouponInput {
    active: boolean;
    couponType: CouponType;
    expiresAt?: Timestamp;
    value: bigint;
    code: string;
    description?: string;
    maxRedemptions?: bigint;
}
export interface CounsellorProfile {
    id: string;
    bio: string;
    title: string;
    published: boolean;
    name: string;
    createdAt: Timestamp;
    photoUrl?: string;
    updatedAt: Timestamp;
    specializations: Array<string>;
}
export interface CareerRecommendation {
    title: string;
    matchPercentage: bigint;
    rationale: string;
    careerId: string;
}
export interface UserProfileInput {
    displayName: string;
    email: string;
}
export interface UserProfile {
    id: UserId;
    emailVerified: boolean;
    displayName: string;
    createdAt: Timestamp;
    passportPurchasedAt?: Timestamp;
    role: UserRole;
    email: string;
    updatedAt: Timestamp;
    suspended: boolean;
    passportPurchased: boolean;
}
export interface AssessmentReport {
    id: UserId;
    maxScore: bigint;
    userId: UserId;
    recommendations: Array<CareerRecommendation>;
    generatedAt: Timestamp;
    breakdown: Array<ScoreBreakdown>;
    assessmentType: AssessmentType;
    totalScore: bigint;
    summary: string;
}
export enum AssessmentType {
    aptitude = "aptitude",
    personality = "personality",
    interest = "interest"
}
export enum CouponType {
    flat = "flat",
    percent = "percent"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    refunded = "refunded",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __assessmentsState(): Promise<any>;
    __careersState(): Promise<any>;
    __contentState(): Promise<any>;
    __couponsState(): Promise<any>;
    __paymentsState(): Promise<any>;
    __proofState(): Promise<any>;
    __reportsState(): Promise<any>;
    __usersState(): Promise<any>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    adminListUsers(searchQuery: AdminUserQuery): Promise<Array<AdminUserView>>;
    adminSearchUsers(searchQuery: AdminUserQuery): Promise<Array<AdminUserView>>;
    adminSuspendUser(userId: Principal): Promise<UserProfile>;
    adminUnsuspendUser(userId: Principal): Promise<UserProfile>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBlogPost(input: BlogPostInput): Promise<BlogPost>;
    createCareer(input: CareerEntryInput): Promise<CareerEntry>;
    createCounsellor(input: CounsellorProfileInput): Promise<CounsellorProfile>;
    createCoupon(input: CouponInput): Promise<Coupon>;
    createEvent(input: EventInput): Promise<Event>;
    deleteBlogPost(id: string): Promise<void>;
    deleteCareer(id: string): Promise<void>;
    deleteCounsellor(id: string): Promise<void>;
    deleteCoupon(code: string): Promise<void>;
    deleteEvent(id: string): Promise<void>;
    generateMyReport(assessmentType: AssessmentType): Promise<AssessmentReport>;
    getBlogPost(id: string): Promise<BlogPost | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCareer(id: string): Promise<CareerEntry | null>;
    getCareerBySlug(slug: string): Promise<CareerEntry | null>;
    getCounsellor(id: string): Promise<CounsellorProfile | null>;
    getEvent(id: string): Promise<Event | null>;
    getMyInvoice(invoiceNumber: string): Promise<Invoice | null>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyProgress(assessmentType: AssessmentType): Promise<AssessmentProgress | null>;
    getMyReport(assessmentType: AssessmentType): Promise<AssessmentReport | null>;
    getProfile(userId: Principal): Promise<UserProfile | null>;
    getReportForUser(userId: Principal, assessmentType: AssessmentType): Promise<AssessmentReport | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllInvoices(): Promise<Array<Invoice>>;
    listAssessmentDefinitions(): Promise<Array<AssessmentDefinition>>;
    listBlogPosts(publishedOnly: boolean): Promise<Array<BlogPost>>;
    listCareers(offset: bigint, limit: bigint): Promise<Array<CareerEntry>>;
    listCounsellors(publishedOnly: boolean): Promise<Array<CounsellorProfile>>;
    listCoupons(): Promise<Array<Coupon>>;
    listEvents(publishedOnly: boolean): Promise<Array<Event>>;
    listMyInvoices(): Promise<Array<Invoice>>;
    listMyReports(): Promise<Array<AssessmentReport>>;
    listProofImages(): Promise<Array<ProofImage>>;
    listProofImagesByCategory(category: string): Promise<Array<ProofImage>>;
    markEmailVerified(userId: Principal): Promise<UserProfile>;
    markPassportPurchased(userId: Principal): Promise<UserProfile>;
    markPaymentCompleted(invoiceNumber: string): Promise<Payment>;
    recordMyPayment(input: RecordPaymentInput): Promise<Payment>;
    saveMyProgress(input: SaveProgressInput): Promise<AssessmentProgress>;
    searchCareers(searchQuery: CareerSearchQuery): Promise<Array<CareerEntry>>;
    submitMyAssessment(assessmentType: AssessmentType): Promise<AssessmentProgress>;
    updateBlogPost(id: string, input: BlogPostInput): Promise<BlogPost>;
    updateCareer(id: string, input: CareerEntryInput): Promise<CareerEntry>;
    updateCounsellor(id: string, input: CounsellorProfileInput): Promise<CounsellorProfile>;
    updateCoupon(code: string, input: CouponInput): Promise<Coupon>;
    updateEvent(id: string, input: EventInput): Promise<Event>;
    upsertMyProfile(input: UserProfileInput): Promise<UserProfile>;
    validateCoupon(code: string, amount: Amount): Promise<CouponValidation>;
}
import type { AdminUserQuery as _AdminUserQuery, AdminUserView as _AdminUserView, Amount as _Amount, AnsweredQuestion as _AnsweredQuestion, AssessmentDefinition as _AssessmentDefinition, AssessmentProgress as _AssessmentProgress, AssessmentReport as _AssessmentReport, AssessmentType as _AssessmentType, BlogPost as _BlogPost, CareerEntry as _CareerEntry, CareerRecommendation as _CareerRecommendation, CareerSearchQuery as _CareerSearchQuery, CounsellorProfile as _CounsellorProfile, CounsellorProfileInput as _CounsellorProfileInput, Coupon as _Coupon, CouponInput as _CouponInput, CouponType as _CouponType, CouponValidation as _CouponValidation, Currency as _Currency, Error as _Error, Event as _Event, Invoice as _Invoice, Payment as _Payment, PaymentStatus as _PaymentStatus, RecordPaymentInput as _RecordPaymentInput, Result as _Result, SaveProgressInput as _SaveProgressInput, ScoreBreakdown as _ScoreBreakdown, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __assessmentsState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__assessmentsState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__assessmentsState();
            return result;
        }
    }
    async __careersState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__careersState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__careersState();
            return result;
        }
    }
    async __contentState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__contentState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__contentState();
            return result;
        }
    }
    async __couponsState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__couponsState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__couponsState();
            return result;
        }
    }
    async __paymentsState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__paymentsState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__paymentsState();
            return result;
        }
    }
    async __proofState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__proofState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__proofState();
            return result;
        }
    }
    async __reportsState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__reportsState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__reportsState();
            return result;
        }
    }
    async __usersState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__usersState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__usersState();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async adminListUsers(arg0: AdminUserQuery): Promise<Array<AdminUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers(to_candid_AdminUserQuery_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers(to_candid_AdminUserQuery_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSearchUsers(arg0: AdminUserQuery): Promise<Array<AdminUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSearchUsers(to_candid_AdminUserQuery_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSearchUsers(to_candid_AdminUserQuery_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSuspendUser(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSuspendUser(arg0);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSuspendUser(arg0);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUnsuspendUser(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnsuspendUser(arg0);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnsuspendUser(arg0);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBlogPost(arg0: BlogPostInput): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0);
                return from_candid_BlogPost_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0);
            return from_candid_BlogPost_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCareer(arg0: CareerEntryInput): Promise<CareerEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createCareer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCareer(arg0);
            return result;
        }
    }
    async createCounsellor(arg0: CounsellorProfileInput): Promise<CounsellorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createCounsellor(to_candid_CounsellorProfileInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CounsellorProfile_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCounsellor(to_candid_CounsellorProfileInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CounsellorProfile_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCoupon(arg0: CouponInput): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(to_candid_CouponInput_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Coupon_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(to_candid_CouponInput_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Coupon_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEvent(arg0: EventInput): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteCareer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCareer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCareer(arg0);
            return result;
        }
    }
    async deleteCounsellor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCounsellor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCounsellor(arg0);
            return result;
        }
    }
    async deleteCoupon(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async generateMyReport(arg0: AssessmentType): Promise<AssessmentReport> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMyReport(to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AssessmentReport_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMyReport(to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AssessmentReport_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCareer(arg0: string): Promise<CareerEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareer(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareer(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCareerBySlug(arg0: string): Promise<CareerEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareerBySlug(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareerBySlug(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCounsellor(arg0: string): Promise<CounsellorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCounsellor(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCounsellor(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInvoice(arg0: string): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInvoice(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInvoice(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgress(arg0: AssessmentType): Promise<AssessmentProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress(to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress(to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReport(arg0: AssessmentType): Promise<AssessmentReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReport(to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReport(to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportForUser(arg0: Principal, arg1: AssessmentType): Promise<AssessmentReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportForUser(arg0, to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportForUser(arg0, to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllInvoices();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllInvoices();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssessmentDefinitions(): Promise<Array<AssessmentDefinition>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssessmentDefinitions();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssessmentDefinitions();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBlogPosts(arg0: boolean): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPosts(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPosts(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCareers(arg0: bigint, arg1: bigint): Promise<Array<CareerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCareers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCareers(arg0, arg1);
            return result;
        }
    }
    async listCounsellors(arg0: boolean): Promise<Array<CounsellorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCounsellors(arg0);
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCounsellors(arg0);
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoupons();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoupons();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEvents(arg0: boolean): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents(arg0);
            return result;
        }
    }
    async listMyInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyInvoices();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyInvoices();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyReports(): Promise<Array<AssessmentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyReports();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyReports();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProofImages(): Promise<Array<ProofImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProofImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProofImages();
            return result;
        }
    }
    async listProofImagesByCategory(arg0: string): Promise<Array<ProofImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProofImagesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProofImagesByCategory(arg0);
            return result;
        }
    }
    async markEmailVerified(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.markEmailVerified(arg0);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markEmailVerified(arg0);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async markPassportPurchased(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.markPassportPurchased(arg0);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPassportPurchased(arg0);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async markPaymentCompleted(arg0: string): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.markPaymentCompleted(arg0);
                return from_candid_Payment_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPaymentCompleted(arg0);
            return from_candid_Payment_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordMyPayment(arg0: RecordPaymentInput): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMyPayment(to_candid_RecordPaymentInput_n64(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Payment_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMyPayment(to_candid_RecordPaymentInput_n64(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Payment_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMyProgress(arg0: SaveProgressInput): Promise<AssessmentProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMyProgress(to_candid_SaveProgressInput_n66(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AssessmentProgress_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMyProgress(to_candid_SaveProgressInput_n66(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AssessmentProgress_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchCareers(arg0: CareerSearchQuery): Promise<Array<CareerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCareers(to_candid_CareerSearchQuery_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCareers(to_candid_CareerSearchQuery_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitMyAssessment(arg0: AssessmentType): Promise<AssessmentProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMyAssessment(to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AssessmentProgress_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMyAssessment(to_candid_AssessmentType_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AssessmentProgress_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBlogPost(arg0: string, arg1: BlogPostInput): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1);
                return from_candid_BlogPost_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1);
            return from_candid_BlogPost_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCareer(arg0: string, arg1: CareerEntryInput): Promise<CareerEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCareer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCareer(arg0, arg1);
            return result;
        }
    }
    async updateCounsellor(arg0: string, arg1: CounsellorProfileInput): Promise<CounsellorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCounsellor(arg0, to_candid_CounsellorProfileInput_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CounsellorProfile_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCounsellor(arg0, to_candid_CounsellorProfileInput_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CounsellorProfile_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCoupon(arg0: string, arg1: CouponInput): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoupon(arg0, to_candid_CouponInput_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Coupon_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoupon(arg0, to_candid_CouponInput_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Coupon_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEvent(arg0: string, arg1: EventInput): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1);
            return result;
        }
    }
    async upsertMyProfile(arg0: UserProfileInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMyProfile(arg0);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMyProfile(arg0);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateCoupon(arg0: string, arg1: Amount): Promise<CouponValidation> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0, arg1);
                return from_candid_CouponValidation_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0, arg1);
            return from_candid_CouponValidation_n70(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminUserView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserView): AdminUserView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_AssessmentDefinition_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentDefinition): AssessmentDefinition {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_AssessmentProgress_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentProgress): AssessmentProgress {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_AssessmentReport_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentReport): AssessmentReport {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_AssessmentType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentType): AssessmentType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_BlogPost_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CounsellorProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CounsellorProfile): CounsellorProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_CouponType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CouponType): CouponType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CouponValidation_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CouponValidation): CouponValidation {
    return from_candid_record_n71(_uploadFile, _downloadFile, value);
}
function from_candid_Coupon_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CareerEntry]): CareerEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CounsellorProfile]): CounsellorProfile | null {
    return value.length === 0 ? null : from_candid_CounsellorProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : from_candid_Coupon_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssessmentProgress]): AssessmentProgress | null {
    return value.length === 0 ? null : from_candid_AssessmentProgress_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssessmentReport]): AssessmentReport | null {
    return value.length === 0 ? null : from_candid_AssessmentReport_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profile: _UserProfile;
}): {
    profile: UserProfile;
} {
    return {
        profile: from_candid_UserProfile_n12(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    emailVerified: boolean;
    displayName: string;
    createdAt: _Timestamp;
    passportPurchasedAt: [] | [_Timestamp];
    role: _UserRole;
    email: string;
    updatedAt: _Timestamp;
    suspended: boolean;
    passportPurchased: boolean;
}): {
    id: UserId;
    emailVerified: boolean;
    displayName: string;
    createdAt: Timestamp;
    passportPurchasedAt?: Timestamp;
    role: UserRole;
    email: string;
    updatedAt: Timestamp;
    suspended: boolean;
    passportPurchased: boolean;
} {
    return {
        id: value.id,
        emailVerified: value.emailVerified,
        displayName: value.displayName,
        createdAt: value.createdAt,
        passportPurchasedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.passportPurchasedAt)),
        role: from_candid_UserRole_n15(_uploadFile, _downloadFile, value.role),
        email: value.email,
        updatedAt: value.updatedAt,
        suspended: value.suspended,
        passportPurchased: value.passportPurchased
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    body: string;
    published: boolean;
    createdAt: _Timestamp;
    slug: string;
    tags: Array<string>;
    publishedAt: [] | [_Timestamp];
    author: string;
    updatedAt: _Timestamp;
    excerpt: string;
}): {
    id: string;
    title: string;
    body: string;
    published: boolean;
    createdAt: Timestamp;
    slug: string;
    tags: Array<string>;
    publishedAt?: Timestamp;
    author: string;
    updatedAt: Timestamp;
    excerpt: string;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        published: value.published,
        createdAt: value.createdAt,
        slug: value.slug,
        tags: value.tags,
        publishedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.publishedAt)),
        author: value.author,
        updatedAt: value.updatedAt,
        excerpt: value.excerpt
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    title: string;
    published: boolean;
    name: string;
    createdAt: _Timestamp;
    photoUrl: [] | [string];
    updatedAt: _Timestamp;
    specializations: Array<string>;
}): {
    id: string;
    bio: string;
    title: string;
    published: boolean;
    name: string;
    createdAt: Timestamp;
    photoUrl?: string;
    updatedAt: Timestamp;
    specializations: Array<string>;
} {
    return {
        id: value.id,
        bio: value.bio,
        title: value.title,
        published: value.published,
        name: value.name,
        createdAt: value.createdAt,
        photoUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.photoUrl)),
        updatedAt: value.updatedAt,
        specializations: value.specializations
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    couponType: _CouponType;
    expiresAt: [] | [_Timestamp];
    value: bigint;
    code: string;
    createdAt: _Timestamp;
    description: [] | [string];
    redemptions: bigint;
    maxRedemptions: [] | [bigint];
}): {
    active: boolean;
    couponType: CouponType;
    expiresAt?: Timestamp;
    value: bigint;
    code: string;
    createdAt: Timestamp;
    description?: string;
    redemptions: bigint;
    maxRedemptions?: bigint;
} {
    return {
        active: value.active,
        couponType: from_candid_CouponType_n30(_uploadFile, _downloadFile, value.couponType),
        expiresAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.expiresAt)),
        value: value.value,
        code: value.code,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.description)),
        redemptions: value.redemptions,
        maxRedemptions: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.maxRedemptions))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    maxScore: bigint;
    userId: _UserId;
    recommendations: Array<_CareerRecommendation>;
    generatedAt: _Timestamp;
    breakdown: Array<_ScoreBreakdown>;
    assessmentType: _AssessmentType;
    totalScore: bigint;
    summary: string;
}): {
    id: UserId;
    maxScore: bigint;
    userId: UserId;
    recommendations: Array<CareerRecommendation>;
    generatedAt: Timestamp;
    breakdown: Array<ScoreBreakdown>;
    assessmentType: AssessmentType;
    totalScore: bigint;
    summary: string;
} {
    return {
        id: value.id,
        maxScore: value.maxScore,
        userId: value.userId,
        recommendations: value.recommendations,
        generatedAt: value.generatedAt,
        breakdown: value.breakdown,
        assessmentType: from_candid_AssessmentType_n37(_uploadFile, _downloadFile, value.assessmentType),
        totalScore: value.totalScore,
        summary: value.summary
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    finalAmount: _Amount;
    userId: _UserId;
    discountAmount: _Amount;
    invoiceNumber: string;
    currency: _Currency;
    issuedAt: _Timestamp;
    coupon: [] | [_Coupon];
    amount: _Amount;
}): {
    status: PaymentStatus;
    finalAmount: Amount;
    userId: UserId;
    discountAmount: Amount;
    invoiceNumber: string;
    currency: Currency;
    issuedAt: Timestamp;
    coupon?: Coupon;
    amount: Amount;
} {
    return {
        status: from_candid_PaymentStatus_n46(_uploadFile, _downloadFile, value.status),
        finalAmount: value.finalAmount,
        userId: value.userId,
        discountAmount: value.discountAmount,
        invoiceNumber: value.invoiceNumber,
        currency: value.currency,
        issuedAt: value.issuedAt,
        coupon: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.coupon)),
        amount: value.amount
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startedAt: _Timestamp;
    submitted: boolean;
    userId: _UserId;
    answers: Array<_AnsweredQuestion>;
    assessmentType: _AssessmentType;
    submittedAt: [] | [_Timestamp];
    lastSavedAt: _Timestamp;
}): {
    startedAt: Timestamp;
    submitted: boolean;
    userId: UserId;
    answers: Array<AnsweredQuestion>;
    assessmentType: AssessmentType;
    submittedAt?: Timestamp;
    lastSavedAt: Timestamp;
} {
    return {
        startedAt: value.startedAt,
        submitted: value.submitted,
        userId: value.userId,
        answers: value.answers,
        assessmentType: from_candid_AssessmentType_n37(_uploadFile, _downloadFile, value.assessmentType),
        submittedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.submittedAt)),
        lastSavedAt: value.lastSavedAt
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    assessmentType: _AssessmentType;
    description: string;
    totalQuestions: bigint;
    durationMinutes: bigint;
}): {
    title: string;
    assessmentType: AssessmentType;
    description: string;
    totalQuestions: bigint;
    durationMinutes: bigint;
} {
    return {
        title: value.title,
        assessmentType: from_candid_AssessmentType_n37(_uploadFile, _downloadFile, value.assessmentType),
        description: value.description,
        totalQuestions: value.totalQuestions,
        durationMinutes: value.durationMinutes
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    completedAt: [] | [_Timestamp];
    couponCode: [] | [string];
    finalAmount: _Amount;
    userId: _UserId;
    discountAmount: _Amount;
    createdAt: _Timestamp;
    invoiceNumber: string;
    currency: _Currency;
    stripeSessionId: [] | [string];
    amount: _Amount;
}): {
    status: PaymentStatus;
    completedAt?: Timestamp;
    couponCode?: string;
    finalAmount: Amount;
    userId: UserId;
    discountAmount: Amount;
    createdAt: Timestamp;
    invoiceNumber: string;
    currency: Currency;
    stripeSessionId?: string;
    amount: Amount;
} {
    return {
        status: from_candid_PaymentStatus_n46(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.completedAt)),
        couponCode: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.couponCode)),
        finalAmount: value.finalAmount,
        userId: value.userId,
        discountAmount: value.discountAmount,
        createdAt: value.createdAt,
        invoiceNumber: value.invoiceNumber,
        currency: value.currency,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.stripeSessionId)),
        amount: value.amount
    };
}
function from_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    valid: boolean;
    discountAmount: _Amount;
    reason: [] | [string];
}): {
    valid: boolean;
    discountAmount: Amount;
    reason?: string;
} {
    return {
        valid: value.valid,
        discountAmount: value.discountAmount,
        reason: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.reason))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flat: null;
} | {
    percent: null;
}): CouponType {
    return "flat" in value ? CouponType.flat : "percent" in value ? CouponType.percent : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aptitude: null;
} | {
    personality: null;
} | {
    interest: null;
}): AssessmentType {
    return "aptitude" in value ? AssessmentType.aptitude : "personality" in value ? AssessmentType.personality : "interest" in value ? AssessmentType.interest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssessmentDefinition>): Array<AssessmentDefinition> {
    return value.map((x)=>from_candid_AssessmentDefinition_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CounsellorProfile>): Array<CounsellorProfile> {
    return value.map((x)=>from_candid_CounsellorProfile_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coupon>): Array<Coupon> {
    return value.map((x)=>from_candid_Coupon_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssessmentReport>): Array<AssessmentReport> {
    return value.map((x)=>from_candid_AssessmentReport_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserView>): Array<AdminUserView> {
    return value.map((x)=>from_candid_AdminUserView_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AdminUserQuery_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminUserQuery): _AdminUserQuery {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_AssessmentType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssessmentType): _AssessmentType {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_CareerSearchQuery_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CareerSearchQuery): _CareerSearchQuery {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_CounsellorProfileInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CounsellorProfileInput): _CounsellorProfileInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CouponInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponInput): _CouponInput {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_CouponType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponType): _CouponType {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_RecordPaymentInput_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordPaymentInput): _RecordPaymentInput {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_SaveProgressInput_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProgressInput): _SaveProgressInput {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    title: string;
    published: boolean;
    name: string;
    photoUrl?: string;
    specializations: Array<string>;
}): {
    bio: string;
    title: string;
    published: boolean;
    name: string;
    photoUrl: [] | [string];
    specializations: Array<string>;
} {
    return {
        bio: value.bio,
        title: value.title,
        published: value.published,
        name: value.name,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        specializations: value.specializations
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    couponType: CouponType;
    expiresAt?: Timestamp;
    value: bigint;
    code: string;
    description?: string;
    maxRedemptions?: bigint;
}): {
    active: boolean;
    couponType: _CouponType;
    expiresAt: [] | [_Timestamp];
    value: bigint;
    code: string;
    description: [] | [string];
    maxRedemptions: [] | [bigint];
} {
    return {
        active: value.active,
        couponType: to_candid_CouponType_n26(_uploadFile, _downloadFile, value.couponType),
        expiresAt: value.expiresAt ? candid_some(value.expiresAt) : candid_none(),
        value: value.value,
        code: value.code,
        description: value.description ? candid_some(value.description) : candid_none(),
        maxRedemptions: value.maxRedemptions ? candid_some(value.maxRedemptions) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roleFilter?: UserRole;
    offset: bigint;
    suspendedFilter?: boolean;
    limit: bigint;
    searchTerm?: string;
    passportFilter?: boolean;
}): {
    roleFilter: [] | [_UserRole];
    offset: bigint;
    suspendedFilter: [] | [boolean];
    limit: bigint;
    searchTerm: [] | [string];
    passportFilter: [] | [boolean];
} {
    return {
        roleFilter: value.roleFilter ? candid_some(to_candid_UserRole_n7(_uploadFile, _downloadFile, value.roleFilter)) : candid_none(),
        offset: value.offset,
        suspendedFilter: value.suspendedFilter ? candid_some(value.suspendedFilter) : candid_none(),
        limit: value.limit,
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        passportFilter: value.passportFilter ? candid_some(value.passportFilter) : candid_none()
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode?: string;
    currency: Currency;
    stripeSessionId?: string;
    amount: Amount;
}): {
    couponCode: [] | [string];
    currency: _Currency;
    stripeSessionId: [] | [string];
    amount: _Amount;
} {
    return {
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        currency: value.currency,
        stripeSessionId: value.stripeSessionId ? candid_some(value.stripeSessionId) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answers: Array<AnsweredQuestion>;
    assessmentType: AssessmentType;
}): {
    answers: Array<_AnsweredQuestion>;
    assessmentType: _AssessmentType;
} {
    return {
        answers: value.answers,
        assessmentType: to_candid_AssessmentType_n33(_uploadFile, _downloadFile, value.assessmentType)
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publishedOnly: boolean;
    offset: bigint;
    limit: bigint;
    searchTerm?: string;
    category?: string;
}): {
    publishedOnly: boolean;
    offset: bigint;
    limit: bigint;
    searchTerm: [] | [string];
    category: [] | [string];
} {
    return {
        publishedOnly: value.publishedOnly,
        offset: value.offset,
        limit: value.limit,
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none()
    };
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponType): {
    flat: null;
} | {
    percent: null;
} {
    return value == CouponType.flat ? {
        flat: null
    } : value == CouponType.percent ? {
        percent: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssessmentType): {
    aptitude: null;
} | {
    personality: null;
} | {
    interest: null;
} {
    return value == AssessmentType.aptitude ? {
        aptitude: null
    } : value == AssessmentType.personality ? {
        personality: null
    } : value == AssessmentType.interest ? {
        interest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
